name: zeb_permissions_helper_example
description: Example app for zeb_permissions_helper package
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  zeb_permissions_helper:
    path: ../
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
