name: zeb_permissions_helper
description: A flexible, customizable permission helper for Flutter apps. Handles permission flows, platform special-cases (iOS notifications / location).
version: 1.1.2
homepage: https://github.com/dev-zeb/zeb_permissions_helper/blob/main/README.md
repository: https://github.com/dev-zeb/zeb_permissions_helper
environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0
  shared_preferences: ^2.3.4
  flutter_local_notifications: ^18.0.1
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.zeb_permissions_helper
        pluginClass: ZebPermissionsHelperPlugin
      ios:
        pluginClass: ZebPermissionsHelperPlugin
