name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*.*.*'  # Runs when you push tags like v1.1.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        env:
          PUB_TOKEN: ${{ secrets.PUB_CREDENTIALS }}
        run: dart pub publish --force
