name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*.*.*' # Trigger when version tags like v1.1.2 are pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Restore pub credentials
        env:
          PUB_TOKEN: ${{ secrets.PUB_CREDENTIALS }}
        run: |
          mkdir -p ~/.pub-cache
          echo "$PUB_TOKEN" > ~/.pub-cache/credentials.json

      - name: Publish (dry-run) to pub.dev
        run: dart pub publish --dry-run

      - name: Publish to pub.dev
        if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
        run: dart pub publish --force # Use --force to skip confirmation
